// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateBoard(ctx context.Context, name string) (Board, error)
	CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteBoard(ctx context.Context, id int32) (Board, error)
	DeleteColumn(ctx context.Context, id int32) (Column, error)
	DeleteTask(ctx context.Context, id int32) (Task, error)
	GetBoard(ctx context.Context, id int32) (Board, error)
	GetColumn(ctx context.Context, id int32) (Column, error)
	GetTask(ctx context.Context, id int32) (Task, error)
	ListBoards(ctx context.Context, arg ListBoardsParams) ([]Board, error)
	ListColumns(ctx context.Context, arg ListColumnsParams) ([]Column, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error)
	UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
