name: Build and deploy Backend to EC2
run-name: "#${{ github.run_number }} - ${{ github.ref_name }} - ${{ github.sha }} - Backend"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: 
      - 'server/**'
      - '.github/workflows/cicd-backend.yml'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'server/**'
      - '.github/workflows/cicd-backend.yml'

env:
  WORKING_DIRECTORY: server

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
        

    - name: Build
      run: go build -v ./...
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Test
      run: go test -v ./...
      working-directory: ${{ env.WORKING_DIRECTORY }}
