name: Build and deploy Backend to EC2
run-name: "#${{ github.run_number }} - ${{ github.ref_name }} - ${{ github.sha }} - Backend"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: 
      - 'server/**'
      - '.github/workflows/cicd-backend.yml'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'server/**'
      - '.github/workflows/cicd-backend.yml'

env:
  WORKING_DIRECTORY: server

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
        

    - name: Build
      run: go build -v ./...
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Test
      run: go test -v ./...
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Update app.env
      run: |
        sed -i "s|^DB_SOURCE=.*|DB_SOURCE=${{ secrets.DB_STRING }}|" app.env
        sed -i "s|^TOKEN_SYMMETRIC_KEY=.*|TOKEN_SYMMETRIC_KEY=${{ secrets.KEY }}|" app.env
          
    - name: Verify app.env
      run: cat app.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Extract metadata (tags, version) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/stegg
        tags: |
          type=raw,value=${{ github.sha }}
  
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
